## - Exercici 1
Agafa un conjunt de dades de tema esportiu que t'agradi. Realitza un mostreig de les dades generant una mostra aleatòria simple i una mostra sistemàtica.

In [62]:
from openpyxl import load_workbook
import pandas as pd
import numpy as np

In [63]:
df = pd.DataFrame(pd.read_excel('Kaggle_Sirio_Libanes_ICU_Prediction.xlsx'))
df.head()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
0,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
1,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0
2,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4-6,0
3,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,NaN,NaN,NaN,NaN,-1.000000,-1.000000,6-12,0
4,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.238095,-0.818182,-0.389967,0.407558,-0.230462,0.096774,-0.242282,-0.814433,ABOVE_12,1

In [64]:
df.shape

(1925, 231)

In [65]:
df.describe(include='object')

       AGE_PERCENTIL WINDOW
count           1925   1925
unique            10      5
top             20th    0-2
freq             215    385

In [66]:
#Numerical Features
cols = df.columns
num_cols = df._get_numeric_data().columns
num_cols

Index(['PATIENT_VISIT_IDENTIFIER', 'AGE_ABOVE65', 'GENDER',
       'DISEASE GROUPING 1', 'DISEASE GROUPING 2', 'DISEASE GROUPING 3',
       'DISEASE GROUPING 4', 'DISEASE GROUPING 5', 'DISEASE GROUPING 6', 'HTN',
       ...
       'RESPIRATORY_RATE_DIFF', 'TEMPERATURE_DIFF', 'OXYGEN_SATURATION_DIFF',
       'BLOODPRESSURE_DIASTOLIC_DIFF_REL', 'BLOODPRESSURE_SISTOLIC_DIFF_REL',
       'HEART_RATE_DIFF_REL', 'RESPIRATORY_RATE_DIFF_REL',
       'TEMPERATURE_DIFF_REL', 'OXYGEN_SATURATION_DIFF_REL', 'ICU'],
      dtype='object', length=229)

In [67]:
df.dtypes

PATIENT_VISIT_IDENTIFIER        int64
AGE_ABOVE65                     int64
AGE_PERCENTIL                  object
GENDER                          int64
DISEASE GROUPING 1            float64
                               ...
RESPIRATORY_RATE_DIFF_REL     float64
TEMPERATURE_DIFF_REL          float64
OXYGEN_SATURATION_DIFF_REL    float64
WINDOW                         object
ICU                             int64
Length: 231, dtype: object

### Probability Sampling

Casos en los que todas las unidades de una población dada tienen la misma probabilidad de ser seleccionadas. Esta técnica incluye muestreo aleatorio simple, muestreo sistemático, muestreo por conglomerados y muestreo aleatorio estratificado.

#### muestreo aleatorio simple

El método de muestreo aleatorio simple selecciona muestras aleatorias de un proceso o población donde cada unidad tiene la misma probabilidad de ser seleccionada. Este es el método más directo de muestreo probabilístico.

In [68]:
# usamos la funcion sample para coger 100 valores aletorios del dataframe
simple_random_sample = df.sample(n=100).sort_values(by='PATIENT_VISIT_IDENTIFIER')

# mostramos los datos
simple_random_sample

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
4,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.238095,-0.818182,-0.389967,0.407558,-0.230462,0.096774,-0.242282,-0.814433,ABOVE_12,1
8,1,1,90th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.880952,-1.000000,-0.906832,-0.831132,-0.940967,-0.817204,-0.882574,-1.000000,6-12,1
9,1,1,90th,1,0.0,0.0,0.0,0.0,1.0,0.0,...,0.142857,-0.797980,0.315690,0.200359,-0.239515,0.645161,0.139709,-0.802317,ABOVE_12,1
44,8,0,50th,0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.238095,-0.898990,-0.701863,-0.571690,-0.719780,-0.741935,-0.240194,-0.898004,ABOVE_12,0
46,9,1,80th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1869,373,1,90th,1,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.476190,-0.838384,-0.493168,-0.123154,-0.624966,0.401434,-0.476190,-0.836806,ABOVE_12,1
1887,377,0,20th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.809524,-0.979798,-0.961590,-0.938413,-0.895824,-1.000000,-0.811606,-0.979709,4-6,0
1900,380,0,40th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
1913,382,0,50th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,6-12,0
1922,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,4-6,0

podemos ver como la media varia en cada ejecucion, aunque se debe manetener en una oquilla

In [69]:
# calculamos la media con redondeo a 5
simple_random_sample = df.sample(n=100).sort_values(by='PATIENT_VISIT_IDENTIFIER')
round(simple_random_sample['TEMPERATURE_DIFF'].mean(),5)

-0.77513

In [70]:
simple_random_sample = df.sample(n=100).sort_values(by='PATIENT_VISIT_IDENTIFIER')
round(simple_random_sample['TEMPERATURE_DIFF'].mean(),5)

-0.75897

In [71]:
simple_random_sample = df.sample(n=100).sort_values(by='PATIENT_VISIT_IDENTIFIER')
round(simple_random_sample['TEMPERATURE_DIFF'].mean(),5)

-0.82353

## muestreo sistemático
El método de muestreo sistemático selecciona unidades en función de un intervalo de muestreo fijo (es decir, cada n-ésima unidad se selecciona de un proceso o población determinados). Este método de muestreo tiende a ser más eficaz que el método de muestreo aleatorio simple.

In [72]:
#funcion que recive el dataframe y los escalones
def systematic_sampling(df, step):
    
    #cogemos el rango escalonado.
    indexes = np.arange(0,len(df),step=step)
    #sampelamos el dataframe con este rango escalonado
    systematic_sample = df.iloc[indexes]
    return systematic_sample
    
# ejecutamos la funcion de sistematic sampler
systematic_sampling(df, 3)

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
0,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
3,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,NaN,NaN,NaN,NaN,-1.000000,-1.000000,6-12,0
6,1,1,90th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,1
9,1,1,90th,1,0.0,0.0,0.0,0.0,1.0,0.0,...,0.142857,-0.797980,0.315690,0.200359,-0.239515,0.645161,0.139709,-0.802317,ABOVE_12,1
12,2,0,10th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,-0.959596,-0.515528,-0.351328,-0.747001,-0.756272,NaN,-0.961262,4-6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,382,0,50th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0
1914,382,0,50th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.500000,-0.838384,-0.513996,-0.236377,-0.617378,-0.191851,-0.498615,-0.835052,ABOVE_12,1
1917,383,0,40th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,4-6,0
1920,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
1923,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,6-12,0

#### muestreo por conglomerados
El método de muestreo por conglomerados divide la población en conglomerados de igual tamaño n y selecciona conglomerados cada T-ésima vez.

In [73]:
def cluster_sampling(df, num_clusters):
    
    try:
        # creamos un array con el id de cada cluster repetido n veces asta llegar a la longitud del dataframe
        df['id'] = np.repeat([range(1,num_clusters+1)],len(df)/num_clusters)
        # Agregar los índices de los clústeres que cumplen con los criterios
        # Para esta fórmula, la identificación de los grupos debe ser un número par
        indexes = [ i for i in range(len(df)) if df['id'].iloc[i]%2 == 0 ]
               
        return(df.iloc[indexes])
    except Exception as e:
        print(f"ERROR:{e}")
        
# hacemos un muestreo de cinco cluster
cluster_sampling(df,5)

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU,id
385,77,1,80th,0,0.0,0.0,1.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0-2,0,2
386,77,1,80th,0,0.0,0.0,1.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-4,0,2
387,77,1,80th,0,0.0,0.0,1.0,0.0,1.0,1.0,...,-0.959596,-0.900621,-0.806115,-0.988114,-0.918757,-0.860232,-0.959631,4-6,1,2
388,77,1,80th,0,0.0,0.0,1.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,6-12,1,2
389,77,1,80th,0,1.0,0.0,1.0,0.0,1.0,1.0,...,-0.737374,-0.373913,-0.147626,-0.436502,-0.365025,-0.452381,-0.734810,ABOVE_12,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535,307,1,70th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0-2,0,4
1536,307,1,70th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0,4
1537,307,1,70th,1,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4-6,0,4
1538,307,1,70th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-0.888696,-0.857230,-0.957325,-0.817204,-1.000000,-1.000000,6-12,1,4
1539,307,1,70th,1,1.0,0.0,0.0,0.0,1.0,0.0,...,-0.858586,-0.588933,-0.458914,-0.699832,0.809677,-0.425397,-0.860180,ABOVE_12,1,4

## - Exercici 2
Continua amb el conjunt de dades de tema esportiu i genera una mostra estratificada i una mostra utilitzant SMOTE (Synthetic Minority Oversampling Technique).

#### Muestreo aleatorio estratificado

El método de muestreo aleatorio estratificado divide la población en subgrupos (es decir, estratos) y selecciona muestras aleatorias donde cada unidad tiene la misma probabilidad de ser seleccionada.

In [74]:
from sklearn.model_selection import StratifiedShuffleSplit

# establecemos el criterio de division
split = StratifiedShuffleSplit(n_splits=4, test_size=100)

# dividimos el dataframe
[df.iloc[y].sort_values(by='PATIENT_VISIT_IDENTIFIER') for x, y in split.split(df, df['AGE_ABOVE65'])]

[      PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65 AGE_PERCENTIL  GENDER  \
 14                           2            0          10th       0
 12                           2            0          10th       0
 45                           9            1          80th       0
 63                          12            0          20th       1
 90                          18            0          20th       0
 ...                        ...          ...           ...     ...
 1873                       374            0          40th       1
 1875                       375            1          70th       1
 1880                       376            1          90th       0
 1888                       377            0          20th       1
 1906                       381            1    Above 90th       0

       DISEASE GROUPING 1  DISEASE GROUPING 2  DISEASE GROUPING 3  \
 14                   0.0                 0.0                 0.0
 12                   0.0                 0.0                 0.0
 45                   0.0                 0.0                 0.0
 63                   0.0                 0.0                 0.0
 90                   0.0                 0.0                 0.0
 ...                  ...                 ...                 ...
 1873                 0.0                 0.0                 0.0
 1875                 1.0                 0.0                 0.0
 1880                 1.0                 1.0                 1.0
 1888                 0.0                 0.0                 0.0
 1906                 0.0                 0.0                 0.0

       DISEASE GROUPING 4  DISEASE GROUPING 5  DISEASE GROUPING 6  ...  \
 14                   0.0                 0.0                 0.0  ...
 12                   0.0                 0.0                 0.0  ...
 45                   0.0                 0.0                 0.0  ...
 63                   0.0                 0.0                 0.0  ...
 90                   0.0                 0.0                 0.0  ...
 ...                  ...                 ...                 ...  ...
 1873                 0.0                 0.0                 0.0  ...
 1875                 0.0                 0.0                 0.0  ...
 1880                 0.0                 1.0                 0.0  ...
 1888                 0.0                 0.0                 0.0  ...
 1906                 0.0                 0.0                 0.0  ...

       OXYGEN_SATURATION_DIFF  BLOODPRESSURE_DIASTOLIC_DIFF_REL  \
 14                 -0.898990                         -0.612422
 12                 -0.959596                         -0.515528
 45                       NaN                               NaN
 63                       NaN                               NaN
 90                       NaN                               NaN
 ...                      ...                               ...
 1873               -1.000000                         -0.986874
 1875               -1.000000                         -1.000000
 1880               -1.000000                         -1.000000
 1888                     NaN                               NaN
 1906                     NaN                               NaN

       BLOODPRESSURE_SISTOLIC_DIFF_REL  HEART_RATE_DIFF_REL  \
 14                          -0.343258            -0.576744
 12                          -0.351328            -0.747001
 45                                NaN                  NaN
 63                                NaN                  NaN
 90                                NaN                  NaN
 ...                               ...                  ...
 1873                        -0.821247            -0.843736
 1875                        -1.000000            -1.000000
 1880                        -1.000000            -1.000000
 1888                              NaN                  NaN
 1906                              NaN                  NaN

       RESPIRATORY_RATE_DIFF_REL  TEMPERATURE_DIFF_REL  \
 14                    -0.695341             -0.505464
 12                    -0.756272                   NaN
 45                          NaN                   NaN
 63                          NaN                   NaN
 90                          NaN                   NaN
 ...                         ...                   ...
 1873                  -1.000000             -0.855949
 1875                        NaN                   NaN
 1880                  -1.000000             -1.000000
 1888                        NaN                   NaN
 1906                        NaN                   NaN

       OXYGEN_SATURATION_DIFF_REL    WINDOW  ICU  id
 14                     -0.900129  ABOVE_12    1   1
 12                     -0.961262       4-6    0   1
 45                           NaN       0-2    0   1
 63                           NaN      6-12    0   1
 90                           NaN       0-2    0   1
 ...                          ...       ...  ...  ..
 1873                   -1.000000      6-12    0   5
 1875                   -1.000000       0-2    0   5
 1880                   -1.000000       0-2    0   5
 1888                         NaN      6-12    0   5
 1906                         NaN       2-4    0   5

 [100 rows x 232 columns],
       PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65 AGE_PERCENTIL  GENDER  \
 38                           7            0          20th       0
 49                           9            1          80th       0
 73                          14            1          60th       1
 85                          17            0          40th       0
 127                         25            1          90th       0
 ...                        ...          ...           ...     ...
 1813                       362            0          10th       0
 1853                       370            0          50th       0
 1867                       373            1          90th       1
 1872                       374            0          40th       1
 1898                       379            1    Above 90th       1

       DISEASE GROUPING 1  DISEASE GROUPING 2  DISEASE GROUPING 3  \
 38                   0.0                 0.0                 0.0
 49                   0.0                 0.0                 0.0
 73                   0.0                 0.0                 0.0
 85                   0.0                 0.0                 0.0
 127                  0.0                 0.0                 0.0
 ...                  ...                 ...                 ...
 1813                 0.0                 0.0                 0.0
 1853                 0.0                 0.0                 0.0
 1867                 0.0                 0.0                 0.0
 1872                 0.0                 0.0                 0.0
 1898                 0.0                 0.0                 0.0

       DISEASE GROUPING 4  DISEASE GROUPING 5  DISEASE GROUPING 6  ...  \
 38                   0.0                 0.0                 0.0  ...
 49                   0.0                 1.0                 0.0  ...
 73                   0.0                 0.0                 0.0  ...
 85                   0.0                 0.0                 0.0  ...
 127                  0.0                 0.0                 0.0  ...
 ...                  ...                 ...                 ...  ...
 1813                 0.0                 0.0                 0.0  ...
 1853                 0.0                 0.0                 0.0  ...
 1867                 0.0                 0.0                 0.0  ...
 1872                 0.0                 0.0                 0.0  ...
 1898                 0.0                 1.0                 0.0  ...

       OXYGEN_SATURATION_DIFF  BLOODPRESSURE_DIASTOLIC_DIFF_REL  \
 38                 -0.979798                         -0.984877
 49                 -0.919192                         -0.739130
 73                 -0.979798                         -0.764850
 85                 -1.000000                         -1.000000
 127                -1.000000                         -1.000000
 ...                      ...                               ...
 1813               -0.979798                         -0.941212
 1853               -1.000000                         -1.000000
 1867               -1.000000                         -1.000000
 1872                     NaN                               NaN
 1898               -0.979798                         -0.764376

       BLOODPRESSURE_SISTOLIC_DIFF_REL  HEART_RATE_DIFF_REL  \
 38                          -0.897259            -0.609781
 49                          -0.663471            -0.808142
 73                          -0.502046            -0.901612
 85                          -1.000000            -1.000000
 127                         -1.000000            -1.000000
 ...                               ...                  ...
 1813                        -0.935636            -0.893314
 1853                        -1.000000            -1.000000
 1867                        -1.000000            -1.000000
 1872                              NaN                  NaN
 1898                        -0.441335            -0.935433

       RESPIRATORY_RATE_DIFF_REL  TEMPERATURE_DIFF_REL  \
 38                    -1.000000             -0.975992
 49                    -0.616129             -0.671208
 73                    -0.780645             -0.772584
 85                    -1.000000             -1.000000
 127                   -1.000000             -1.000000
 ...                         ...                   ...
 1813                  -0.506452             -0.929545
 1853                  -1.000000             -1.000000
 1867                  -1.000000             -1.000000
 1872                        NaN                   NaN
 1898                  -0.746898             -0.835380

       OXYGEN_SATURATION_DIFF_REL    WINDOW  ICU  id
 38                     -0.980026      6-12    0   1
 49                     -0.918403  ABOVE_12    0   1
 73                     -0.979816      6-12    1   1
 85                     -1.000000       0-2    1   1
 127                    -1.000000       4-6    0   1
 ...                          ...       ...  ...  ..
 1813                   -0.979601      6-12    1   5
 1853                   -1.000000      6-12    0   5
 1867                   -1.000000       4-6    1   5
 1872                         NaN       4-6    0   5
 1898                   -0.980631      6-12    1   5

 [100 rows x 232 columns],
       PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65 AGE_PERCENTIL  GENDER  \
 1                            0            1          60th       0
 13                           2            0          10th       0
 16                           3            0          40th       1
 56                          11            1          80th       0
 64                          12            0          20th       1
 ...                        ...          ...           ...     ...
 1770                       354            0          60th       1
 1789                       357            1          80th       0
 1808                       361            0          20th       0
 1817                       363            1          90th       0
 1895                       379            1    Above 90th       1

       DISEASE GROUPING 1  DISEASE GROUPING 2  DISEASE GROUPING 3  \
 1                    0.0                 0.0                 0.0
 13                   0.0                 0.0                 0.0
 16                   0.0                 0.0                 0.0
 56                   0.0                 0.0                 0.0
 64                   0.0                 0.0                 0.0
 ...                  ...                 ...                 ...
 1770                 0.0                 0.0                 0.0
 1789                 1.0                 1.0                 1.0
 1808                 0.0                 0.0                 1.0
 1817                 0.0                 0.0                 0.0
 1895                 0.0                 0.0                 0.0

       DISEASE GROUPING 4  DISEASE GROUPING 5  DISEASE GROUPING 6  ...  \
 1                    0.0                 1.0                 1.0  ...
 13                   0.0                 0.0                 0.0  ...
 16                   0.0                 0.0                 0.0  ...
 56                   0.0                 0.0                 0.0  ...
 64                   0.0                 0.0                 0.0  ...
 ...                  ...                 ...                 ...  ...
 1770                 0.0                 0.0                 0.0  ...
 1789                 0.0                 1.0                 0.0  ...
 1808                 1.0                 0.0                 1.0  ...
 1817                 0.0                 0.0                 0.0  ...
 1895                 0.0                 0.0                 0.0  ...

       OXYGEN_SATURATION_DIFF  BLOODPRESSURE_DIASTOLIC_DIFF_REL  \
 1                  -1.000000                         -1.000000
 13                 -0.797980                         -0.658863
 16                       NaN                               NaN
 56                       NaN                               NaN
 64                 -0.878788                         -0.697543
 ...                      ...                               ...
 1770               -1.000000                         -1.000000
 1789               -0.838384                         -0.478261
 1808               -1.000000                         -1.000000
 1817                     NaN                               NaN
 1895               -0.959596                         -0.799034

       BLOODPRESSURE_SISTOLIC_DIFF_REL  HEART_RATE_DIFF_REL  \
 1                           -1.000000            -1.000000
 13                          -0.563758            -0.721834
 16                                NaN                  NaN
 56                                NaN                  NaN
 64                          -0.338750            -0.551918
 ...                               ...                  ...
 1770                        -1.000000            -1.000000
 1789                        -0.287248            -0.613773
 1808                        -0.863437            -0.806096
 1817                              NaN                  NaN
 1895                        -0.796630            -0.937704

       RESPIRATORY_RATE_DIFF_REL  TEMPERATURE_DIFF_REL  \
 1                     -1.000000             -1.000000
 13                    -0.926882             -1.000000
 16                          NaN                   NaN
 56                          NaN                   NaN
 64                    -0.612903             -0.498615
 ...                         ...                   ...
 1770                  -1.000000             -1.000000
 1789                  -0.341935             -0.612627
 1808                  -1.000000             -0.732554
 1817                        NaN                   NaN
 1895                  -0.846962             -0.976483

       OXYGEN_SATURATION_DIFF_REL    WINDOW  ICU  id
 1                      -1.000000       2-4    0   1
 13                     -0.801293      6-12    0   1
 16                           NaN       2-4    0   1
 56                           NaN       2-4    0   1
 64                     -0.881390  ABOVE_12    0   1
 ...                          ...       ...  ...  ..
 1770                   -1.000000       0-2    0   5
 1789                   -0.838524  ABOVE_12    1   5
 1808                   -1.000000      6-12    0   5
 1817                         NaN       4-6    0   5
 1895                   -0.961262       0-2    1   5

 [100 rows x 232 columns],
       PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65 AGE_PERCENTIL  GENDER  \
 5                            1            1          90th       1
 17                           3            0          40th       1
 40                           8            0          50th       0
 86                          17            0          40th       0
 109                         21            1          70th       0
 ...                        ...          ...           ...     ...
 1790                       358            1          70th       0
 1816                       363            1          90th       0
 1835                       367            1          90th       1
 1850                       370            0          50th       0
 1874                       374            0          40th       1

       DISEASE GROUPING 1  DISEASE GROUPING 2  DISEASE GROUPING 3  \
 5                    0.0                 0.0                 0.0
 17                   0.0                 0.0                 0.0
 40                   0.0                 0.0                 0.0
 86                   0.0                 0.0                 0.0
 109                  0.0                 0.0                 0.0
 ...                  ...                 ...                 ...
 1790                 0.0                 0.0                 0.0
 1816                 0.0                 0.0                 0.0
 1835                 1.0                 0.0                 1.0
 1850                 0.0                 0.0                 0.0
 1874                 0.0                 0.0                 0.0

       DISEASE GROUPING 4  DISEASE GROUPING 5  DISEASE GROUPING 6  ...  \
 5                    0.0                 0.0                 0.0  ...
 17                   0.0                 0.0                 0.0  ...
 40                   0.0                 0.0                 0.0  ...
 86                   0.0                 0.0                 0.0  ...
 109                  0.0                 0.0                 0.0  ...
 ...                  ...                 ...                 ...  ...
 1790                 0.0                 0.0                 0.0  ...
 1816                 0.0                 0.0                 0.0  ...
 1835                 0.0                 1.0                 0.0  ...
 1850                 0.0                 0.0                 0.0  ...
 1874                 0.0                 0.0                 0.0  ...

       OXYGEN_SATURATION_DIFF  BLOODPRESSURE_DIASTOLIC_DIFF_REL  \
 5                  -1.000000                         -1.000000
 17                 -1.000000                         -1.000000
 40                       NaN                         -1.000000
 86                 -1.000000                         -0.674614
 109                -0.898990                         -0.652174
 ...                      ...                               ...
 1790               -0.858586                         -1.000000
 1816                     NaN                               NaN
 1835                     NaN                               NaN
 1850                     NaN                               NaN
 1874               -0.919192                         -0.621739

       BLOODPRESSURE_SISTOLIC_DIFF_REL  HEART_RATE_DIFF_REL  \
 5                           -1.000000            -1.000000
 17                          -1.000000            -1.000000
 40                          -1.000000            -1.000000
 86                          -0.931292            -0.957153
 109                         -0.685906            -0.804501
 ...                               ...                  ...
 1790                        -1.000000            -1.000000
 1816                              NaN                  NaN
 1835                              NaN                  NaN
 1850                              NaN                  NaN
 1874                        -0.541946            -0.527735

       RESPIRATORY_RATE_DIFF_REL  TEMPERATURE_DIFF_REL  \
 5                     -1.000000             -1.000000
 17                    -1.000000             -1.000000

## - Exercici 3
Continua amb el conjunt de dades de tema esportiu i genera una mostra utilitzant el mètode Reservoir sampling.

El reservoir sampling es una familia de algoritmos aleatorios para elegir aleatoriamente k muestras de una lista de n elementos, donde n es un número muy grande o desconocido. Por lo general, n es lo suficientemente grande como para que la lista no quepa en la memoria principal.

In [75]:
import random
def reservoir_sampling(df, k):
    indexes = []
    n = 0
    df['id']=range(1, len(df) + 1)
    for index in df['id']:
        n = n + 1
        if len(indexes) < k:
            indexes.append(index)
        else:
            j = int(random.random() * n)
            if j < k:
                indexes[j] = index
    
    return df.iloc[indexes]

reservoir_sampling(df,100)

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU,id
810,162,0,30th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,0-2,0,811
444,88,0,10th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.838384,-0.445941,-0.365467,-0.358015,0.632408,-0.358914,-0.840206,ABOVE_12,1,445
1630,326,1,90th,1,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0-2,0,1631
1560,312,0,20th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0-2,0,1561
1744,348,0,40th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.838384,-0.543478,-0.565886,-0.270064,0.039049,-0.425397,-0.838524,ABOVE_12,0,1745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1807,361,0,20th,0,0.0,0.0,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4-6,0,1808
825,165,0,30th,0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0-2,0,826
1821,364,1,90th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,1,1822
892,178,0,50th,0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.919192,-0.986957,-0.897856,-0.940967,-0.451613,-1.000000,-0.916629,4-6,0,893
1716,343,1,80th,1,0.0,0.0,0.0,0.0,1.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0,1717